packages/client/src/components/SafeContacts.js
packages/client/src/components/SafeSettings.js
packages/client/src/hooks/useClipboard.js
packages/client/src/pages/Safe.js

I couldn't find a corresponding Linear task for this, but let me know if there is one / if one should be made.
- `useClipboard` hook is a simplified, dependency-less version of [this](https://github.com/wsmd/use-clipboard-copy) library
- I opted to use [`navigator.clipboard`](https://caniuse.com/?search=navigator.clipboard), but let me know if browser support is a concern (I would assume IE is a non-issue)
- The interstitial text is just "Copied" right now, happy to change that if there's something else it should be
- I did add one new location that I saw in the Figma mocks but not the current app:
Let me know if I missed any spots, or if any other new ones should be added!

add new useClipboard hook, hook up copy address buttons

---

packages/client/src/components/SafeOwners.js
packages/client/src/pages/LoadSafe.js

| Fix      | Screenshot |
| ----------- | ----------- |
| We require "Owner name" and "Owner address" to always be specified in terms of the form disabling, but they did not have the required asterisk like other required fields do. Added to these places. | <img width="1484" alt="Screen Shot 2022-05-15 at 6 13 35 PM" src="https://user-images.githubusercontent.com/2916671/168496132-4892253b-9463-4efa-a5ff-5eef469fb314.png">       |
| Fixed copy & pasted placeholder in load safe view   | <img width="1490" alt="Screen Shot 2022-05-15 at 6 13 23 PM" src="https://user-images.githubusercontent.com/2916671/168496133-057fbd21-7e0f-476e-bf07-58c6f60f4b6d.png">        |
Let me know if any of these changes don't make sense.

add required asterisk to more fields, fix an input placeholder

---

packages/client/src/App.sass
packages/client/src/pages/Home.js

| Before      | After |
| ----------- | ----------- |
| <img width="1073" alt="Screen Shot 2022-05-16 at 2 48 49 PM" src="https://user-images.githubusercontent.com/2916671/168661873-02f64d22-d849-4aae-b778-5bb394c77b47.png">      | <img width="1072" alt="Screen Shot 2022-05-16 at 2 49 08 PM" src="https://user-images.githubusercontent.com/2916671/168661908-de2688d7-586c-41d5-bd51-a86eb90cbbda.png">       |

fix typo on home page, rounded background color behind sidebar

---

packages/client/src/components/SafeContacts.js
packages/client/src/components/SafeDetails.js
packages/client/src/components/SafeOwners.js
packages/client/src/components/SafeSettings.js
packages/client/src/hooks/useClipboard.js
packages/client/src/hooks/useTreasury.js
packages/client/src/pages/LoadSafe.js
packages/client/src/pages/Safe.js
packages/client/src/reducers/index.js

- Added `border-light` to some inputs that weren't matching designs
- Refactored `useClipboard` hook to return a `textJustCopied` value instead of a boolean so that it can be used for multiple values
- Hooked up "Copy" for address in safe settings
- Added new `<EditSafeName />` modal component, hooked up to "Edit" in safe settings
https://user-images.githubusercontent.com/2916671/172436257-5193e30b-f6b7-49c6-a7d3-3b444af3d03c.mov

VSL-22: hook up address copying and name editing from safe settings

---

contracts/DAOTreasury.cdc
contracts/MyMultiSig.cdc
contracts/TreasuryActions.cdc

* Adds events to `DAOTreasury.cdc`
* Adds events to `MyMultiSig.cdc`
* Adds events to `TreasuryActions.cdc`
Some of these events are a little redundant, because I wasn't 100% sure which events would be the most useful.
Some of these events also might not contain all the context the front-end needs to query them properly.  We will need to play around with the Events API to determine whether we need to enrich any of these events further to serve the FE needs.

VSL-43: Add Events to VESSEL Contracts

---

README.md

add instructions for running `fcl-dev-wallet`, this should change once the implementation via the flow cli works locally. also adds link for funding a testnet flow account with tokens

update readme for dev wallet + testnet flow

---

contracts/DAOTreasury.cdc
contracts/MyMultiSig.cdc
main_test.go
scripts/get_total_verified_for_action.cdc
test_utils.go
transactions/signer_approve.cdc
transactions/signer_revoke.cdc

- adds `MultiSignAction.signerRevokeApproval` function for signers to revoke their approval of an action
- refactor `MultiSignAction.validateSignature` function to just generally validate whether a message signature is valid.  Validation of the message structure is now the responsibility of the functions that need to validate signatures (i.e. `signerApproveAction` and `signerRevokeApproval`)
- Updates tests + `signer_approve.cdc` tx to adhere to new payload that `signerApproveAction` expects
- Adds `TestSignerRevokeApproval` test

VSL-60: QSP-7 Allow Signers to Revoke their Approval

---

packages/client/src/components/ActionsList.js

**Issue**:
After adding a new owner, when threshold remains as 1, the signatures number under "Thing to do" become `0 of 2 signatures` as it's using the number of signers.
**Fix**:
The total number of signatures required should be the threshold number.
After fix:

fix number of signatures in UI

---

go.mod
go.sum
packages/client/src/flow/addSigner.tx.js
packages/client/src/flow/removeSigner.tx.js
packages/client/src/flow/updateThreshold.tx.js
test_utils.go
transactions/add_signer.cdc
transactions/destroy_action.cdc
transactions/propose_non_fungible_token_transfer_to_treasury.cdc
transactions/remove_signer.cdc
transactions/update_threshold.cdc

Updated go to 1.18.0
Updated overflow, cadence, flow-go-sdk and other dependencies
Updated transactions and tests as a result from updating libraries

VSL-106: Updated versions so overflow testing works with emulator

---

contracts/DAOTreasury.cdc
contracts/MyMultiSig.cdc
flow.json
scripts/validate_signature_v2.cdc

Lowered from 1000 to 999 total weight of the keys so that signing the message from one user works with Blocto wallet
More context on this thread: https://brud.slack.com/archives/C03ERT4F2MB/p1659551174397049 
Nothing to be shown, should fix the error when the contracts are deployed

VSL-115: Reverted keys weight to 999 to enable Blocto signing

---

packages/client/src/hooks/useTreasury.js
packages/client/src/pages/CreateSafe.js
packages/client/src/reducers/treasuries.js

This pr fixed the issue described in [this ticket](https://linear.app/dappercollectives/issue/VSL-82/safe-creating-page-remains-persistent-after-canceling): after clicking cancel button on the second step of creating a safe, when user wants to create a safe again, user should be able to start with a blank canvas
https://user-images.githubusercontent.com/7423845/183758737-d5af4424-ad7d-487c-99a9-e8a71a53e3f3.mov

VSL-82: Safe Creating Page remains persistent after canceling

---

packages/client/src/pages/LoadSafe.js

This pr fixes the bug reported in ticket https://linear.app/dappercollectives/issue/VSL-111/owner-list-is-empty-after-load-safe
After loading a safe, safe settings page should display safe owners
https://user-images.githubusercontent.com/7423845/184228535-4d71e3b1-bd5c-4c82-9881-9d3742a22ded.mov

VSL-111: Bug fix Owner list is empty after load safe

---

packages/client/src/components/SafeSettings.js

As per the requirements of this ticket https://linear.app/dappercollectives/issue/VSL-92/prevent-remove-button-if-only-one-owner-fe-work, adds logic to prevent rendering remove button when there's only one owner in the list
https://user-images.githubusercontent.com/7423845/184389633-15092587-106c-497a-8fb5-3f80f00ed8c3.mov

hide remove link when there's only one owner on the list

---

packages/client/src/App.js

I was getting 401 invalid API token error from FlowGraph, turns out it was due to missing ENV with proper API key. 
After updating Fleek config with correct REACT_APP_FLOWGRAPH_API_KEY:
Getting CORS error:
As per FlowGraph Doc, it's recommended to use frontend query string instead. So I updated the setup in this PR.
https://docs.flowgraph.co/#2-front-end-usage-url-query-string
Not able to test it out as it doesn't work on emulator. Will verify it on stage.

Update FlowGraph setup

---

packages/client/src/components/TestToolBox.js
packages/client/src/hooks/useTreasury.js

**Issue**:
if test account does not have FUSD vault, deposit token will throw exception:
In this PR moved FUSD setup as optional step, so that if user doesn't have FUSD vault, FLOW tokens can still be deposited successfully.
After this change, deposit token will work with no issues and error msg on depositing FUSD will be logged in console:

Updated TestToolBox to avoid exception

---

contracts/MyMultiSig.cdc
packages/client/src/components/TestToolBox.js
packages/client/src/contexts/Web3.js
packages/client/src/hooks/useTreasury.js
packages/client/src/pages/Safe.js

Enabling signing with Lilico and Blocto
For Lilico the problem was verifying the hashing algorithm which is different than Blocto
For Blocto the problem was that on testnet it started returning both keys for signing the messages - temporary solution is to use the one with 999 weight, until we research how to send and validate both
`make test`

VSL-142: Enable signing with Lilico and Blocto

---

packages/client/src/App.js

use `HashRouter` so that refreshing on IPFS deploys doesn't break the app

switch to HashRouter for IPFS deploys

---

packages/client/src/pages/LoadSafe.js

remove the need to give a name to every signer when loading safe, removing the required asterisk and validation logic.

dont require name for loading safe

---

packages/client/src/hooks/useTreasury.js
packages/client/src/pages/CreateSafe.js
packages/client/src/reducers/treasuries.js

This pr fixes the bug of creating page persists after reconnect with a wallet
**Steps to Reproduce**
- With a connected Flow wallet, initiate safe creation by clicking the "create a new safe" button.
- Fill in the required information in the safe creation form and click the "sign & authorize" button.
- From the "Safe creating" processing page click the "Cancel" button.
- Once redirected to the landing page, disconnect from the current wallet and connect to a different wallet
- Re-initiate safe creation by clicking the "create a new safe"  button.
**Expected Behavior:**
User is presented with a new safe-create page.
**Actual Behavior:**
User is directed to the previous "Safe Creating" processing page. 
https://user-images.githubusercontent.com/7423845/187275720-cb4e9b40-c8a9-42ee-bbeb-8dfc3 …

VSL 148: Safe Creating Page remains persistent after connecting with a new wallet bug

---

packages/client/src/components/SignatureRequirements.js
packages/client/src/pages/CreateSafe.js

- limit the amount of signatures required to be no greater than the amount of safe owners added.

limit signature requirements to not exceed amount of safe owners

---

packages/client/src/components/TestToolBox.js
packages/client/src/flow/getAccountBalanceByContractName.tx.js

This pr fixes the front-end errors related to the testtoolbox
- Have the script return balance of 0 if user doesn't have a vault set up, to get rid of this error:
- conditional render the test tool box list items, to get rid of this error:

VSL-166: return balance of 0 if user doesn't have a vault set up

---

contracts/MyMultiSig.cdc
contracts/TreasuryActions.cdc
main_test.go
test_utils.go
transactions/add_signer_update_threshold.cdc
transactions/remove_signer_update_threshold.cdc

- Adds `AddSignerUpdateThreshold` and `RemoveSignerUpdateThreshold` actions to `treasury_actions.cdc`
- Replace `TestAddSignerAction` test with `TestAddSignerUpdateThresholdAction`
- Replace `TestRemoveSignerAction` test with `TestRemoveSignerUpdateThresholdAction`
Now it is possible to add/remove a signer to/from a treasury AND update the threshold in the same action.
Once FE is integrated we can remove `AddSigner` and `RemoveSigner` actions.
`make test`

VSL-163: AddSignerUpdateThreshold and RemoveSignerUpdateThreshold actions

---

packages/client/src/contexts/Modal.js

Fixes issue where once headerTitle is set, it gets appended to future modals because we're not clearing the modal state properly.

reset default value of headerTitle when reusing modals

---

packages/client/.eslintrc.json
packages/client/.prettierrc
packages/client/package.json
yarn.lock

Borrow the `prettier` setup from [CAST](https://github.com/DapperCollectives/CAST/blob/main/frontend/packages/client/.prettierrc) so that we can easily format our files while developing and correct small issues automatically with `eslint --fix` + `prettier --write`.

add prettier setup from CAST
